### ISSUE TITLE
@Forbidden annotation

### ISSUE THREAD

**Issue by szymonsobocik** [FutureProcessing/document-juggler#14]
Should specify which methods in Model interfaces are forbidden in which contexts.

For example:
@Forbidden({QUERY})  //but allowed in update and insert
Model withSomething(String s)

**Comment by exys666** [comment]
What are you think about merging UnsupportedMethodException with ForbiddenActionException?
Technically getters are forbidden in e.g Update context.  I don't see any reasons why we should have two separates exceptions.

**Comment by szymonsobocik** [comment]
@exys666 Looks OK. We could merge it together. `ForbiddenActionException` or `ForbiddenOperationException` are ok.
