### ISSUE TITLE
Test for _id field that is not ObjectId

### ISSUE THREAD

**Issue by szymonsobocik** [FutureProcessing/document-juggler#19]
Write tests where field _id is:
- `String`
- `Integer`
- `int`
- `ObjectId`

Don't use `@ObjectId` annotation

**Comment by pcmiel** [comment]
For now allowed is only _id as ObjectId, because method insert(...) in BaseRepository return String (cast from ObjectID). My propositions to fix this are: 
1) insert(...) should return _id as Object;
2) type of _id should be parameterized in MODEL;
